#!/usr/bin/env python3
"""Generate docker-compose.yml with a given number of PBS compute node services.

Compose's --scale/deploy.replicas can't give each replica a unique hostname or
env var, which PBS nodes need (distinct hostname/PBS_NODENAME). Rather than
work around that at runtime, this script generates one explicit service per
node, matching the pbsnode[1-10] range the server pre-declares at startup.

Usage:
    ./generate-compose.py [--nodes N] [--output FILE]
"""
import argparse

HEADER = """# Generated by generate-compose.py --nodes {nodes}. Do not hand-edit the
# pbsnode service blocks below; re-run the script to change the node count.
x-node-common: &node-common
  build:
    context: ./mom
    args:
      UBUNTU_BASE: ${{UBUNTU_BASE}}
  image: ghcr.io/noaa-gsl/dockerpbscluster/pbs-mom:${{IMAGE_TAG}}
  shm_size: '4g'
  user: admin
  volumes:
    - shared-vol:/home/admin
  depends_on:
    pbsserver:
      condition: service_started
    pbsfrontend:
      condition: service_healthy
  healthcheck:
    test: ["CMD", "ssh", "-o", "StrictHostKeyChecking=no", "admin@localhost", "hostname"]
    interval: 10s
    timeout: 5s
    retries: 5

services:
  pbsfrontend:
    build:
      context: ./frontend
      args:
        UBUNTU_BASE: ${{UBUNTU_BASE}}
    image: ghcr.io/noaa-gsl/dockerpbscluster/pbs-frontend:${{IMAGE_TAG}}
    container_name: ${{CLUSTER_NAME}}-frontend
    shm_size: '4g'
    hostname: pbsfrontend
    user: admin
    volumes:
      - shared-vol:/home/admin
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/ssh-ready"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 5s
  pbsserver:
    build:
      context: ./server
      args:
        UBUNTU_BASE: ${{UBUNTU_BASE}}
    image: ghcr.io/noaa-gsl/dockerpbscluster/pbs-server:${{IMAGE_TAG}}
    container_name: ${{CLUSTER_NAME}}-server
    shm_size: '4g'
    hostname: pbsserver
    user: admin
    volumes:
      - shared-vol:/home/admin
    depends_on:
      pbsfrontend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/pbs-server-ready"]
      interval: 5s
      timeout: 3s
      retries: 60
      start_period: 10s
"""

NODE_TEMPLATE = """  pbsnode{n}:
    <<: *node-common
    container_name: ${{CLUSTER_NAME}}-node{n}
    hostname: pbsnode{n}
    environment:
      - PBS_NODENAME=pbsnode{n}
"""

FOOTER = """volumes:
  shared-vol:
"""

MAX_NODES = 10


def build_compose(nodes: int) -> str:
    if not 1 <= nodes <= MAX_NODES:
        raise ValueError(f"--nodes must be between 1 and {MAX_NODES} (the PBS server pre-declares pbsnode[1-{MAX_NODES}])")
    parts = [HEADER.format(nodes=nodes)]
    parts.extend(NODE_TEMPLATE.format(n=i) for i in range(1, nodes + 1))
    parts.append(FOOTER)
    return "".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--nodes", type=int, default=3, help="number of pbsnode services to generate (default: 3, max: %d)" % MAX_NODES)
    parser.add_argument("--output", default="docker-compose.yml", help="output file path (default: docker-compose.yml)")
    args = parser.parse_args()

    compose = build_compose(args.nodes)
    with open(args.output, "w") as f:
        f.write(compose)
    print(f"Wrote {args.output} with {args.nodes} node service(s).")


if __name__ == "__main__":
    main()
